/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as test from "./test";
export type { test };
export type { LoanBook } from "./LoanBook";
export type { PoolManagement } from "./PoolManagement";
export type { StakingOperations } from "./StakingOperations";
export type { StakingPool } from "./StakingPool";
export type { StakingPoolStorage } from "./StakingPoolStorage";
