/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface LoanBookInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "approveLiquidation"
      | "createLoan"
      | "executeLiquidation"
      | "fundLoan"
      | "loanCount"
      | "loans"
      | "lockCollateral"
      | "markDefaulted"
      | "owner"
      | "recordRepayment"
      | "releaseCollateral"
      | "renounceOwnership"
      | "startGracePeriod"
      | "startLiquidationReview"
      | "transferOwnership"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "CollateralLocked"
      | "CollateralReleased"
      | "LiquidationApproved"
      | "LiquidationExecuted"
      | "LiquidationReviewStarted"
      | "LoanClosed"
      | "LoanCreated"
      | "LoanDefaulted"
      | "LoanFunded"
      | "LoanGracePeriodStarted"
      | "OwnershipTransferred"
      | "RepaymentRecorded"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "approveLiquidation",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createLoan",
    values: [
      AddressLike,
      AddressLike,
      AddressLike,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      boolean
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "executeLiquidation",
    values: [BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "fundLoan",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "loanCount", values?: undefined): string;
  encodeFunctionData(functionFragment: "loans", values: [BigNumberish]): string;
  encodeFunctionData(
    functionFragment: "lockCollateral",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "markDefaulted",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "recordRepayment",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "releaseCollateral",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "startGracePeriod",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "startLiquidationReview",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "approveLiquidation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "createLoan", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "executeLiquidation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "fundLoan", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "loanCount", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "loans", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "lockCollateral",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "markDefaulted",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "recordRepayment",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "releaseCollateral",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "startGracePeriod",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "startLiquidationReview",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
}

export namespace CollateralLockedEvent {
  export type InputTuple = [
    loanId: BigNumberish,
    collateralAsset: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [
    loanId: bigint,
    collateralAsset: string,
    amount: bigint
  ];
  export interface OutputObject {
    loanId: bigint;
    collateralAsset: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CollateralReleasedEvent {
  export type InputTuple = [
    loanId: BigNumberish,
    collateralAsset: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [
    loanId: bigint,
    collateralAsset: string,
    amount: bigint
  ];
  export interface OutputObject {
    loanId: bigint;
    collateralAsset: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace LiquidationApprovedEvent {
  export type InputTuple = [loanId: BigNumberish];
  export type OutputTuple = [loanId: bigint];
  export interface OutputObject {
    loanId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace LiquidationExecutedEvent {
  export type InputTuple = [
    loanId: BigNumberish,
    recoveredAmount: BigNumberish,
    shortfallAmount: BigNumberish
  ];
  export type OutputTuple = [
    loanId: bigint,
    recoveredAmount: bigint,
    shortfallAmount: bigint
  ];
  export interface OutputObject {
    loanId: bigint;
    recoveredAmount: bigint;
    shortfallAmount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace LiquidationReviewStartedEvent {
  export type InputTuple = [loanId: BigNumberish];
  export type OutputTuple = [loanId: bigint];
  export interface OutputObject {
    loanId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace LoanClosedEvent {
  export type InputTuple = [loanId: BigNumberish];
  export type OutputTuple = [loanId: bigint];
  export interface OutputObject {
    loanId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace LoanCreatedEvent {
  export type InputTuple = [
    loanId: BigNumberish,
    borrower: AddressLike,
    borrowAsset: AddressLike,
    collateralAsset: AddressLike,
    principalAmount: BigNumberish,
    collateralAmount: BigNumberish,
    serviceFeeAmount: BigNumberish
  ];
  export type OutputTuple = [
    loanId: bigint,
    borrower: string,
    borrowAsset: string,
    collateralAsset: string,
    principalAmount: bigint,
    collateralAmount: bigint,
    serviceFeeAmount: bigint
  ];
  export interface OutputObject {
    loanId: bigint;
    borrower: string;
    borrowAsset: string;
    collateralAsset: string;
    principalAmount: bigint;
    collateralAmount: bigint;
    serviceFeeAmount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace LoanDefaultedEvent {
  export type InputTuple = [loanId: BigNumberish];
  export type OutputTuple = [loanId: bigint];
  export interface OutputObject {
    loanId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace LoanFundedEvent {
  export type InputTuple = [
    loanId: BigNumberish,
    borrowAsset: AddressLike,
    principalAmount: BigNumberish,
    nextDueAt: BigNumberish
  ];
  export type OutputTuple = [
    loanId: bigint,
    borrowAsset: string,
    principalAmount: bigint,
    nextDueAt: bigint
  ];
  export interface OutputObject {
    loanId: bigint;
    borrowAsset: string;
    principalAmount: bigint;
    nextDueAt: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace LoanGracePeriodStartedEvent {
  export type InputTuple = [
    loanId: BigNumberish,
    gracePeriodEndsAt: BigNumberish
  ];
  export type OutputTuple = [loanId: bigint, gracePeriodEndsAt: bigint];
  export interface OutputObject {
    loanId: bigint;
    gracePeriodEndsAt: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RepaymentRecordedEvent {
  export type InputTuple = [
    loanId: BigNumberish,
    amount: BigNumberish,
    principalAppliedAmount: BigNumberish,
    serviceFeeAppliedAmount: BigNumberish,
    outstandingPrincipalAmount: BigNumberish,
    outstandingServiceFeeAmount: BigNumberish
  ];
  export type OutputTuple = [
    loanId: bigint,
    amount: bigint,
    principalAppliedAmount: bigint,
    serviceFeeAppliedAmount: bigint,
    outstandingPrincipalAmount: bigint,
    outstandingServiceFeeAmount: bigint
  ];
  export interface OutputObject {
    loanId: bigint;
    amount: bigint;
    principalAppliedAmount: bigint;
    serviceFeeAppliedAmount: bigint;
    outstandingPrincipalAmount: bigint;
    outstandingServiceFeeAmount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface LoanBook extends BaseContract {
  connect(runner?: ContractRunner | null): LoanBook;
  waitForDeployment(): Promise<this>;

  interface: LoanBookInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  approveLiquidation: TypedContractMethod<
    [loanId: BigNumberish],
    [void],
    "nonpayable"
  >;

  createLoan: TypedContractMethod<
    [
      borrower: AddressLike,
      borrowAsset: AddressLike,
      collateralAsset: AddressLike,
      principalAmount: BigNumberish,
      collateralAmount: BigNumberish,
      serviceFeeAmount: BigNumberish,
      installmentAmount: BigNumberish,
      installmentCount: BigNumberish,
      termMonths: BigNumberish,
      autopayEnabled: boolean
    ],
    [bigint],
    "nonpayable"
  >;

  executeLiquidation: TypedContractMethod<
    [
      loanId: BigNumberish,
      recoveredAmount: BigNumberish,
      shortfallAmount: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  fundLoan: TypedContractMethod<
    [loanId: BigNumberish, firstDueAt: BigNumberish],
    [void],
    "payable"
  >;

  loanCount: TypedContractMethod<[], [bigint], "view">;

  loans: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        boolean,
        bigint,
        bigint
      ] & {
        borrower: string;
        borrowAsset: string;
        collateralAsset: string;
        principalAmount: bigint;
        collateralAmount: bigint;
        serviceFeeAmount: bigint;
        outstandingPrincipalAmount: bigint;
        outstandingServiceFeeAmount: bigint;
        installmentAmount: bigint;
        installmentCount: bigint;
        termMonths: bigint;
        nextDueAt: bigint;
        autopayEnabled: boolean;
        state: bigint;
        collateralState: bigint;
      }
    ],
    "view"
  >;

  lockCollateral: TypedContractMethod<
    [loanId: BigNumberish, amount: BigNumberish],
    [void],
    "payable"
  >;

  markDefaulted: TypedContractMethod<
    [loanId: BigNumberish],
    [void],
    "nonpayable"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  recordRepayment: TypedContractMethod<
    [loanId: BigNumberish, amount: BigNumberish],
    [void],
    "payable"
  >;

  releaseCollateral: TypedContractMethod<
    [loanId: BigNumberish],
    [void],
    "nonpayable"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  startGracePeriod: TypedContractMethod<
    [loanId: BigNumberish, gracePeriodEndsAt: BigNumberish],
    [void],
    "nonpayable"
  >;

  startLiquidationReview: TypedContractMethod<
    [loanId: BigNumberish],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "approveLiquidation"
  ): TypedContractMethod<[loanId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "createLoan"
  ): TypedContractMethod<
    [
      borrower: AddressLike,
      borrowAsset: AddressLike,
      collateralAsset: AddressLike,
      principalAmount: BigNumberish,
      collateralAmount: BigNumberish,
      serviceFeeAmount: BigNumberish,
      installmentAmount: BigNumberish,
      installmentCount: BigNumberish,
      termMonths: BigNumberish,
      autopayEnabled: boolean
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "executeLiquidation"
  ): TypedContractMethod<
    [
      loanId: BigNumberish,
      recoveredAmount: BigNumberish,
      shortfallAmount: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "fundLoan"
  ): TypedContractMethod<
    [loanId: BigNumberish, firstDueAt: BigNumberish],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "loanCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "loans"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        boolean,
        bigint,
        bigint
      ] & {
        borrower: string;
        borrowAsset: string;
        collateralAsset: string;
        principalAmount: bigint;
        collateralAmount: bigint;
        serviceFeeAmount: bigint;
        outstandingPrincipalAmount: bigint;
        outstandingServiceFeeAmount: bigint;
        installmentAmount: bigint;
        installmentCount: bigint;
        termMonths: bigint;
        nextDueAt: bigint;
        autopayEnabled: boolean;
        state: bigint;
        collateralState: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "lockCollateral"
  ): TypedContractMethod<
    [loanId: BigNumberish, amount: BigNumberish],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "markDefaulted"
  ): TypedContractMethod<[loanId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "recordRepayment"
  ): TypedContractMethod<
    [loanId: BigNumberish, amount: BigNumberish],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "releaseCollateral"
  ): TypedContractMethod<[loanId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "startGracePeriod"
  ): TypedContractMethod<
    [loanId: BigNumberish, gracePeriodEndsAt: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "startLiquidationReview"
  ): TypedContractMethod<[loanId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "CollateralLocked"
  ): TypedContractEvent<
    CollateralLockedEvent.InputTuple,
    CollateralLockedEvent.OutputTuple,
    CollateralLockedEvent.OutputObject
  >;
  getEvent(
    key: "CollateralReleased"
  ): TypedContractEvent<
    CollateralReleasedEvent.InputTuple,
    CollateralReleasedEvent.OutputTuple,
    CollateralReleasedEvent.OutputObject
  >;
  getEvent(
    key: "LiquidationApproved"
  ): TypedContractEvent<
    LiquidationApprovedEvent.InputTuple,
    LiquidationApprovedEvent.OutputTuple,
    LiquidationApprovedEvent.OutputObject
  >;
  getEvent(
    key: "LiquidationExecuted"
  ): TypedContractEvent<
    LiquidationExecutedEvent.InputTuple,
    LiquidationExecutedEvent.OutputTuple,
    LiquidationExecutedEvent.OutputObject
  >;
  getEvent(
    key: "LiquidationReviewStarted"
  ): TypedContractEvent<
    LiquidationReviewStartedEvent.InputTuple,
    LiquidationReviewStartedEvent.OutputTuple,
    LiquidationReviewStartedEvent.OutputObject
  >;
  getEvent(
    key: "LoanClosed"
  ): TypedContractEvent<
    LoanClosedEvent.InputTuple,
    LoanClosedEvent.OutputTuple,
    LoanClosedEvent.OutputObject
  >;
  getEvent(
    key: "LoanCreated"
  ): TypedContractEvent<
    LoanCreatedEvent.InputTuple,
    LoanCreatedEvent.OutputTuple,
    LoanCreatedEvent.OutputObject
  >;
  getEvent(
    key: "LoanDefaulted"
  ): TypedContractEvent<
    LoanDefaultedEvent.InputTuple,
    LoanDefaultedEvent.OutputTuple,
    LoanDefaultedEvent.OutputObject
  >;
  getEvent(
    key: "LoanFunded"
  ): TypedContractEvent<
    LoanFundedEvent.InputTuple,
    LoanFundedEvent.OutputTuple,
    LoanFundedEvent.OutputObject
  >;
  getEvent(
    key: "LoanGracePeriodStarted"
  ): TypedContractEvent<
    LoanGracePeriodStartedEvent.InputTuple,
    LoanGracePeriodStartedEvent.OutputTuple,
    LoanGracePeriodStartedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "RepaymentRecorded"
  ): TypedContractEvent<
    RepaymentRecordedEvent.InputTuple,
    RepaymentRecordedEvent.OutputTuple,
    RepaymentRecordedEvent.OutputObject
  >;

  filters: {
    "CollateralLocked(uint256,address,uint256)": TypedContractEvent<
      CollateralLockedEvent.InputTuple,
      CollateralLockedEvent.OutputTuple,
      CollateralLockedEvent.OutputObject
    >;
    CollateralLocked: TypedContractEvent<
      CollateralLockedEvent.InputTuple,
      CollateralLockedEvent.OutputTuple,
      CollateralLockedEvent.OutputObject
    >;

    "CollateralReleased(uint256,address,uint256)": TypedContractEvent<
      CollateralReleasedEvent.InputTuple,
      CollateralReleasedEvent.OutputTuple,
      CollateralReleasedEvent.OutputObject
    >;
    CollateralReleased: TypedContractEvent<
      CollateralReleasedEvent.InputTuple,
      CollateralReleasedEvent.OutputTuple,
      CollateralReleasedEvent.OutputObject
    >;

    "LiquidationApproved(uint256)": TypedContractEvent<
      LiquidationApprovedEvent.InputTuple,
      LiquidationApprovedEvent.OutputTuple,
      LiquidationApprovedEvent.OutputObject
    >;
    LiquidationApproved: TypedContractEvent<
      LiquidationApprovedEvent.InputTuple,
      LiquidationApprovedEvent.OutputTuple,
      LiquidationApprovedEvent.OutputObject
    >;

    "LiquidationExecuted(uint256,uint256,uint256)": TypedContractEvent<
      LiquidationExecutedEvent.InputTuple,
      LiquidationExecutedEvent.OutputTuple,
      LiquidationExecutedEvent.OutputObject
    >;
    LiquidationExecuted: TypedContractEvent<
      LiquidationExecutedEvent.InputTuple,
      LiquidationExecutedEvent.OutputTuple,
      LiquidationExecutedEvent.OutputObject
    >;

    "LiquidationReviewStarted(uint256)": TypedContractEvent<
      LiquidationReviewStartedEvent.InputTuple,
      LiquidationReviewStartedEvent.OutputTuple,
      LiquidationReviewStartedEvent.OutputObject
    >;
    LiquidationReviewStarted: TypedContractEvent<
      LiquidationReviewStartedEvent.InputTuple,
      LiquidationReviewStartedEvent.OutputTuple,
      LiquidationReviewStartedEvent.OutputObject
    >;

    "LoanClosed(uint256)": TypedContractEvent<
      LoanClosedEvent.InputTuple,
      LoanClosedEvent.OutputTuple,
      LoanClosedEvent.OutputObject
    >;
    LoanClosed: TypedContractEvent<
      LoanClosedEvent.InputTuple,
      LoanClosedEvent.OutputTuple,
      LoanClosedEvent.OutputObject
    >;

    "LoanCreated(uint256,address,address,address,uint256,uint256,uint256)": TypedContractEvent<
      LoanCreatedEvent.InputTuple,
      LoanCreatedEvent.OutputTuple,
      LoanCreatedEvent.OutputObject
    >;
    LoanCreated: TypedContractEvent<
      LoanCreatedEvent.InputTuple,
      LoanCreatedEvent.OutputTuple,
      LoanCreatedEvent.OutputObject
    >;

    "LoanDefaulted(uint256)": TypedContractEvent<
      LoanDefaultedEvent.InputTuple,
      LoanDefaultedEvent.OutputTuple,
      LoanDefaultedEvent.OutputObject
    >;
    LoanDefaulted: TypedContractEvent<
      LoanDefaultedEvent.InputTuple,
      LoanDefaultedEvent.OutputTuple,
      LoanDefaultedEvent.OutputObject
    >;

    "LoanFunded(uint256,address,uint256,uint256)": TypedContractEvent<
      LoanFundedEvent.InputTuple,
      LoanFundedEvent.OutputTuple,
      LoanFundedEvent.OutputObject
    >;
    LoanFunded: TypedContractEvent<
      LoanFundedEvent.InputTuple,
      LoanFundedEvent.OutputTuple,
      LoanFundedEvent.OutputObject
    >;

    "LoanGracePeriodStarted(uint256,uint256)": TypedContractEvent<
      LoanGracePeriodStartedEvent.InputTuple,
      LoanGracePeriodStartedEvent.OutputTuple,
      LoanGracePeriodStartedEvent.OutputObject
    >;
    LoanGracePeriodStarted: TypedContractEvent<
      LoanGracePeriodStartedEvent.InputTuple,
      LoanGracePeriodStartedEvent.OutputTuple,
      LoanGracePeriodStartedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "RepaymentRecorded(uint256,uint256,uint256,uint256,uint256,uint256)": TypedContractEvent<
      RepaymentRecordedEvent.InputTuple,
      RepaymentRecordedEvent.OutputTuple,
      RepaymentRecordedEvent.OutputObject
    >;
    RepaymentRecorded: TypedContractEvent<
      RepaymentRecordedEvent.InputTuple,
      RepaymentRecordedEvent.OutputTuple,
      RepaymentRecordedEvent.OutputObject
    >;
  };
}
