export const INCIDENT_PACKAGE_RECENT_LIMIT_MAX = 100;
export const INCIDENT_PACKAGE_TIMELINE_LIMIT_MAX = 500;
export const INCIDENT_PACKAGE_EXPORT_SINCE_DAYS_MAX = 90;
export const INCIDENT_PACKAGE_RELEASE_REPORTING_LIMIT_MAX = 100;
export const INCIDENT_PACKAGE_RELEASE_REPORTING_SINCE_DAYS_MAX = 365;
